"""Live dashboard — Flask server with filtering, sorting, and auto-refresh."""

import json
from datetime import datetime
from pathlib import Path

from flask import Flask, jsonify, render_template_string, request

from orchestrator.state_manager import get_recent_deals, init_db, get_price_history

app = Flask(__name__)

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Weekend Deal Hunter — Live</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: #0d0d0d; color: #e0e0e0; font-family: -apple-system, sans-serif; padding: 1.5rem; }
h1 { font-size: 1.6rem; margin-bottom: 0.25rem; }
.subtitle { color: #888; margin-bottom: 1rem; font-size: 0.9rem; }
.controls { display: flex; gap: 0.8rem; flex-wrap: wrap; margin-bottom: 1.5rem; align-items: center; }
.controls label { color: #aaa; font-size: 0.85rem; }
.controls select, .controls input {
  background: #1a1a1a; color: #e0e0e0; border: 1px solid #333;
  padding: 0.4rem 0.6rem; border-radius: 4px; font-size: 0.85rem;
}
.controls button {
  background: #22c55e; color: #000; border: none; padding: 0.4rem 1rem;
  border-radius: 4px; cursor: pointer; font-weight: 600; font-size: 0.85rem;
}
.controls button:hover { background: #16a34a; }
.count { color: #888; font-size: 0.85rem; margin-bottom: 1rem; }
.card { background: #1a1a1a; border-radius: 8px; padding: 1.2rem; margin-bottom: 1rem; }
.card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
.card h2 { font-size: 1.2rem; }
.badge { color: #000; font-weight: 700; padding: 0.15rem 0.6rem; border-radius: 4px; font-size: 0.9rem; }
.meta { color: #888; font-size: 0.85rem; margin-bottom: 0.4rem; }
.line { margin: 0.3rem 0; }
.label-text { color: #aaa; font-size: 0.85rem; }
.mono { font-family: 'Cascadia Code', 'Fira Code', monospace; font-size: 0.85rem; }
.total { font-size: 1.1rem; font-weight: 700; color: #22c55e; margin: 0.5rem 0; font-family: monospace; }
.drop { color: #22c55e; font-weight: 700; }
.increase { color: #ef4444; }
details { margin-top: 0.5rem; }
summary { cursor: pointer; color: #888; font-size: 0.85rem; }
.recs { white-space: pre-wrap; font-size: 0.82rem; color: #ccc; margin-top: 0.4rem; }
table { margin-top: 0.4rem; width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 0.25rem 0.6rem; border-bottom: 1px solid #333; color: #ccc; font-size: 0.85rem; }
th { color: #888; }
.empty { text-align: center; padding: 3rem; color: #666; }
footer { text-align: center; color: #555; font-size: 0.75rem; margin-top: 2rem; }
@media (max-width: 640px) { body { padding: 0.75rem; } .controls { flex-direction: column; } }
</style>
</head>
<body>
<h1>&#9992;&#65039; Weekend Deal Hunter — Live</h1>
<div class="subtitle">Origin: PHL &middot; Last refresh: <span id="refresh-time"></span></div>

<div class="controls">
  <div>
    <label>Max price: $</label>
    <input type="number" id="maxPrice" value="1000" min="0" step="50" style="width:80px;">
  </div>
  <div>
    <label>Min score:</label>
    <input type="number" id="minScore" value="0" min="0" max="100" step="5" style="width:70px;">
  </div>
  <div>
    <label>Destination:</label>
    <select id="destFilter"><option value="">All</option></select>
  </div>
  <div>
    <label>Nonstop only:</label>
    <input type="checkbox" id="nonstopOnly">
  </div>
  <div>
    <label>Sort by:</label>
    <select id="sortBy">
      <option value="score">Score</option>
      <option value="price">Price (low)</option>
      <option value="destination">Destination</option>
    </select>
  </div>
  <button onclick="fetchDeals()">Refresh</button>
</div>

<div class="count" id="count"></div>
<div id="deals"></div>

<footer>Generated by Weekend Deal Hunter &middot; Auto-refreshes every 60s</footer>

<script>
let allDeals = [];

function esc(s) { // Escapes HTML to prevent XSS
  let d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

function scoreColor(s) {
  if (s >= 70) return '#22c55e';
  if (s >= 55) return '#eab308';
  return '#ef4444';
}

function stars(r) {
  let full = Math.floor(r);
  return '\\u2605'.repeat(full) + '\\u2606'.repeat(5 - full);
}

function renderCard(d) {
  let score = d.score || 0;
  let color = scoreColor(score);
  let layovers = d.layovers || 0;
  let stops = layovers === 0 ? 'Nonstop' : layovers + ' stop' + (layovers > 1 ? 's' : '');
  let best = d.best_stay || {};
  let est = d.estimated_total || d.total_trip_cost || 0;
  let drop = d.price_drop;
  let dropText = '';
  if (drop > 0) dropText = ' ↓ $' + drop.toFixed(0) + ' drop';
  else if (drop < 0) dropText = ' ↑ $' + Math.abs(drop).toFixed(0);

  let card = document.createElement('div');
  card.className = 'card';
  card.style.borderLeft = '4px solid ' + color;

  let header = document.createElement('div');
  header.className = 'card-header';
  let h2 = document.createElement('h2');
  h2.textContent = d.destination || '?';
  let badge = document.createElement('span');
  badge.className = 'badge';
  badge.style.background = color;
  badge.textContent = score;
  header.appendChild(h2);
  header.appendChild(badge);
  card.appendChild(header);

  function addMeta(text) {
    let div = document.createElement('div');
    div.className = 'meta';
    div.textContent = text;
    card.appendChild(div);
  }
  function addLine(label, text) {
    let div = document.createElement('div');
    div.className = 'line';
    let sp1 = document.createElement('span');
    sp1.className = 'label-text';
    sp1.textContent = label;
    let sp2 = document.createElement('span');
    sp2.className = 'mono';
    sp2.textContent = ' ' + text;
    div.appendChild(sp1);
    div.appendChild(sp2);
    card.appendChild(div);
  }

  addMeta((d.outbound_date||'') + ' → ' + (d.return_date||''));
  addLine('Flight:', '$' + (d.price_usd||0).toFixed(0) + ' · ' + esc(d.airline||'') + ' · ' + stops +
    ' · ' + (d.outbound_depart||'') + '→' + (d.outbound_arrive||'') +
    ' / ' + (d.return_depart||'') + '→' + (d.return_arrive||''));
  addLine('Hotel:', esc(best.name||'N/A') + ' · $' + (best.total_price||0).toFixed(0) + ' · ' + stars(best.rating||0));

  let totalDiv = document.createElement('div');
  totalDiv.className = 'total';
  totalDiv.textContent = 'Est. Total: $' + est.toFixed(2) + dropText;
  card.appendChild(totalDiv);

  addMeta((d.hours_at_destination||0).toFixed(1) + ' hours at destination');

  // Recommendations
  let details1 = document.createElement('details');
  let sum1 = document.createElement('summary');
  sum1.textContent = 'Recommendations';
  details1.appendChild(sum1);
  let pre = document.createElement('pre');
  pre.className = 'recs';
  pre.textContent = d.recommendations || 'N/A';
  details1.appendChild(pre);
  card.appendChild(details1);

  // All stays
  if (d.all_stays && d.all_stays.length) {
    let details2 = document.createElement('details');
    let sum2 = document.createElement('summary');
    sum2.textContent = 'All Stays (' + d.all_stays.length + ')';
    details2.appendChild(sum2);
    let tbl = document.createElement('table');
    let thead = document.createElement('tr');
    ['Name','Total','Rating','Source'].forEach(function(h) {
      let th = document.createElement('th');
      th.textContent = h;
      thead.appendChild(th);
    });
    tbl.appendChild(thead);
    d.all_stays.slice(0,5).forEach(function(s) {
      let tr = document.createElement('tr');
      [s.name||'', '$'+(s.total_price||0), (s.rating||0).toFixed(1), s.source||s.type||''].forEach(function(v) {
        let td = document.createElement('td');
        td.textContent = v;
        tr.appendChild(td);
      });
      tbl.appendChild(tr);
    });
    details2.appendChild(tbl);
    card.appendChild(details2);
  }

  return card;
}

function applyFilters() {
  let maxPrice = parseFloat(document.getElementById('maxPrice').value) || 9999;
  let minScore = parseFloat(document.getElementById('minScore').value) || 0;
  let dest = document.getElementById('destFilter').value;
  let nonstop = document.getElementById('nonstopOnly').checked;
  let sortBy = document.getElementById('sortBy').value;

  let filtered = allDeals.filter(function(d) {
    let price = d.estimated_total || d.total_trip_cost || 0;
    if (price > maxPrice) return false;
    if ((d.score || 0) < minScore) return false;
    if (dest && d.destination !== dest) return false;
    if (nonstop && (d.layovers || 0) > 0) return false;
    return true;
  });

  if (sortBy === 'price') filtered.sort(function(a,b) { return (a.estimated_total||0) - (b.estimated_total||0); });
  else if (sortBy === 'destination') filtered.sort(function(a,b) { return (a.destination||'').localeCompare(b.destination||''); });
  else filtered.sort(function(a,b) { return (b.score||0) - (a.score||0); });

  document.getElementById('count').textContent = filtered.length + ' deals shown';
  let container = document.getElementById('deals');
  container.replaceChildren();  // Safe DOM clear
  if (filtered.length === 0) {
    let empty = document.createElement('div');
    empty.className = 'empty';
    empty.textContent = 'No deals match your filters.';
    container.appendChild(empty);
  } else {
    filtered.forEach(function(d) { container.appendChild(renderCard(d)); });
  }
}

async function fetchDeals() {
  try {
    let resp = await fetch('/api/deals');
    allDeals = await resp.json();

    let select = document.getElementById('destFilter');
    let current = select.value;
    let dests = [...new Set(allDeals.map(function(d) { return d.destination; }).filter(Boolean))].sort();

    // Safe rebuild of select options
    while (select.options.length > 1) select.remove(1);
    dests.forEach(function(d) {
      let opt = document.createElement('option');
      opt.value = d;
      opt.textContent = d;
      select.appendChild(opt);
    });
    select.value = current;

    applyFilters();
    document.getElementById('refresh-time').textContent = new Date().toLocaleTimeString();
  } catch (e) {
    let container = document.getElementById('deals');
    container.replaceChildren();
    let msg = document.createElement('div');
    msg.className = 'empty';
    msg.textContent = 'Error loading deals.';
    container.appendChild(msg);
  }
}

['maxPrice', 'minScore', 'destFilter', 'nonstopOnly', 'sortBy'].forEach(function(id) {
  document.getElementById(id).addEventListener('change', applyFilters);
  document.getElementById(id).addEventListener('input', applyFilters);
});

fetchDeals();
setInterval(fetchDeals, 60000);
</script>
</body>
</html>"""


@app.route("/")
def index():
    return render_template_string(TEMPLATE)


@app.route("/api/deals")
def api_deals():
    """Return recent deals as JSON for the live dashboard."""
    init_db()
    deals = get_recent_deals(limit=50)
    return jsonify(deals)


@app.route("/api/price-history/<destination>/<outbound_date>")
def api_price_history(destination, outbound_date):
    """Return price history for a specific route."""
    history = get_price_history(destination, outbound_date)
    return jsonify(history)
